complete -c docker-logs -f -s v -l verbose -d 'Display running commands'
complete -c docker-logs -f -l line -d 'Display lines colorized'
complete -c docker-logs -f -s q -l quiet -d 'Quiet mode'
complete -c docker-logs -f -l no-color -d 'Display without colors'
complete -c docker-logs -f -s a -l all -d 'Display stopped containers'
complete -c docker-logs -f -l tail -d 'Display last lines'
complete -c docker-logs -f -l since -d 'Display logs since date'
complete -c docker-logs -f -l until -d 'Display logs until date'
complete -c docker-logs -f -l before-yesterday -d 'Logs since 2 days ago until yesterday'
complete -c docker-logs -f -l yesterday -d 'Logs yesterday'
complete -c docker-logs -f -l today -d 'Logs today'
complete -c docker-logs -f -l now -d 'Logs since 3 minutes ago'
complete -c docker-logs -f -l clear -d 'Clear logs, this locks `docker logs`'
