complete -c update -f -a crates -d 'Update rust crates'
complete -c update -f -a env -d 'Update environment utilities'
complete -c update -f -a go-packages -d 'Update go packages'
complete -c update -f -a lsp -d 'Update development helpers'
complete -c update -f -a lsp-c -d 'Update development helpers'
complete -c update -f -a lsp-composer -d 'Update development helpers'
complete -c update -f -a lsp-java -d 'Update development helpers'
complete -c update -f -a lsp-lsp -d 'Update development helpers'
complete -c update -f -a lsp-npm -d 'Update development helpers'
complete -c update -f -a lsp-npm-install -d 'Update development helpers'
complete -c update -f -a lsp-pip -d 'Update development helpers'
complete -c update -f -a pip -d 'Update python pip'
complete -c update -f -a python-packages -d 'Update python packages'
complete -c update -f -a rust -d 'Update rust compiler'
complete -c update -f -a typst -d 'Update typst compiler'
complete -c update -f -a venv-all -d 'Update pip and development helpers inside environment'
complete -c update -f -a venv-lsp -d 'Update development helpers inside environment'
complete -c update -f -a venv-pip -d 'Update python pip inside environment'
complete -c update -f -a youtube-dl -d 'Update youtube downloader'
complete -c update -f -l update -d 'Update bash completions'
